-- 消息表
CREATE TABLE IF NOT EXISTS message (
    message_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message_type INT NOT NULL DEFAULT 1,
    content VARCHAR(2000),
    file_url VARCHAR(500),
    file_name VARCHAR(200),
    file_size BIGINT,
    reply_to_id BIGINT,
    is_recalled TINYINT(1) NOT NULL DEFAULT 0,
    recalled_at DATETIME NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 用户表
CREATE TABLE IF NOT EXISTS app_user (
    user_id BIGINT PRIMARY KEY,
    nickname VARCHAR(100),
    avatar VARCHAR(500),
    username VARCHAR(100),
    password VARCHAR(200),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
