/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RecentRoomTable: typeof import('./src/components/dashboard/RecentRoomTable.vue')['default']
    RoomStatusPieChart: typeof import('./src/components/dashboard/RoomStatusPieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    TrendLineChart: typeof import('./src/components/dashboard/TrendLineChart.vue')['default']
    VoiceCallBarChart: typeof import('./src/components/dashboard/VoiceCallBarChart.vue')['default']
  }
}
