# P6Spy配置文件
# 指定应用的驱动
driverlist=com.mysql.cj.jdbc.Driver
# 日期格式
dateformat=yyyy-MM-dd HH:mm:ss
# 是否开启慢SQL记录
outagedetection=true
# 慢SQL记录标准，单位秒
outagedetectioninterval=2
# 日志输出到控制台
appender=com.p6spy.engine.spy.appender.StdoutLogger
# 使用p6spy的日志格式化
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
# 自定义日志格式
customLogMessageFormat=当前时间：%(currentTime) | 执行耗时：%(executionTime)ms | 连接信息：%(category)-%(connectionId) | 执行语句：%(sql)
# 不输出包含的语句
excludecategories=info,debug,result,batc,resultset